# Streamlit Secrets Configuration for Deployment
# Configure these in your deployment platform (Streamlit Cloud, etc.)
# DO NOT commit this file to version control

# API Configuration - Point to your deployed backend
API_BASE_URL = "https://your-backend-url.railway.app"  # Change to your deployed backend URL

# Authentication settings (set ENABLE_AUTH = true for public deployment)
ENABLE_AUTH = false  # Set to true for public deployment
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "your-secure-password-change-this"

# Optional: Additional security settings
MAX_REQUESTS_PER_MINUTE = 60
SESSION_TIMEOUT_MINUTES = 30 